### PR TITLE
Added a restart button

### PR DESCRIPTION
**Pull request by jatinEP**
I modified main.jsx and Player.jsx to add a restart button

### CODE REVIEW

**Comment by mustache-dev** [comment]
this is very cool, thanks for your contribution, anyway i'm going to have to refuse the PR : 

The build you made doesn't work on Vercel, it looks like your code is breaking the production, I believe you might have forgot a commit before PR

Please, ask to merge into another branch, thank you

**Comment by jatinEP** [comment]
But how do I do so?

**Comment by mustache-dev** [comment]
Once you fork the project you mustn't write on main but on another branch, and then push to this other branch.

Make your feature work and I will merge it into main

**Comment by jatinEP** [comment]
I will try doing so :D

**Pull request closed without merging**
