### PR TITLE
feat: use pnpm as dependencies

### PR DESCRIPTION
**Pull request by Lantianyou**

### CODE REVIEW

**Comment by Lantianyou** [comment]
1. It is considered best practice using `===` instead of `==` in JavaScript
2. I slightly changed readme to add pnpm
3. I will add TypeScript, eslint and prettier in the future.

**Comment by Lantianyou** [comment]
A few explainations about my changes:

1. [pnpm](https://pnpm.io) is a package management CLI. Unlike Go or Rust, they have great first-party package management tools, `npm` the JavaScript's package management is problematic some times. So people built `pnpm` to improve it, it is 5x~10x faster downloading dependencies and has great documentation. Lots of companies and developers use it, like the CEO of Vercel himself https://twitter.com/rauchg/status/1638665406562041857. This project is built by vite, vite also use `pnpm`. 

2. `@vitejs/plugin-react-swc` is a plugin for vite. It has same functionalities but faster than the `@vitejs/plugin-react`, since it is built upon Rust written `swc`. https://swc.rs/

**Comment by Lantianyou** [comment]
In summary, I believe using `pnpm` and `react-swc` will bring faster downloading project and faster compilation, and it does not require a single line of change to the code inside `src` directory.

**Review by mustache-dev — APPROVED** [review]
Great addition to the project, adding pnpm and SWC is a very nice opportunity to optimize the developer experience, huge thanks Lantianyou

**Pull request merged**
